/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductType = IDL.Variant({
  'Shirt' : IDL.Null,
  'Skirt' : IDL.Null,
  'Pant' : IDL.Null,
  'Suit' : IDL.Null,
  'Shorts' : IDL.Null,
  'Dress' : IDL.Null,
  'Sweater' : IDL.Null,
  'TShirt' : IDL.Null,
  'Jacket' : IDL.Null,
  'Other' : IDL.Text,
  'Blazer' : IDL.Null,
  'Jeans' : IDL.Null,
});
export const ProductSize = IDL.Variant({
  'L' : IDL.Null,
  'M' : IDL.Null,
  'S' : IDL.Null,
  'XL' : IDL.Null,
  'XS' : IDL.Null,
  'XXL' : IDL.Null,
  'Custom' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'productType' : ProductType,
  'sizes' : IDL.Vec(ProductSize),
  'stockCount' : IDL.Nat,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'user' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'products' : IDL.Vec(Product),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'instagram' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'instagramQr' : ExternalBlob,
});
export const ProductFilter = IDL.Record({
  'size' : IDL.Opt(ProductSize),
  'isAvailable' : IDL.Opt(IDL.Bool),
  'productType' : IDL.Opt(ProductType),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'searchText' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getFilteredProducts' : IDL.Func(
      [ProductFilter],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getOrderById' : IDL.Func([IDL.Text], [OrderRecord], ['query']),
  'getOrdersByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OrderRecord)],
      ['query'],
    ),
  'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
  'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([OrderRecord], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminContactInfo' : IDL.Func([ContactInfo], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateProductImages' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductType = IDL.Variant({
    'Shirt' : IDL.Null,
    'Skirt' : IDL.Null,
    'Pant' : IDL.Null,
    'Suit' : IDL.Null,
    'Shorts' : IDL.Null,
    'Dress' : IDL.Null,
    'Sweater' : IDL.Null,
    'TShirt' : IDL.Null,
    'Jacket' : IDL.Null,
    'Other' : IDL.Text,
    'Blazer' : IDL.Null,
    'Jeans' : IDL.Null,
  });
  const ProductSize = IDL.Variant({
    'L' : IDL.Null,
    'M' : IDL.Null,
    'S' : IDL.Null,
    'XL' : IDL.Null,
    'XS' : IDL.Null,
    'XXL' : IDL.Null,
    'Custom' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'productType' : ProductType,
    'sizes' : IDL.Vec(ProductSize),
    'stockCount' : IDL.Nat,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'user' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'products' : IDL.Vec(Product),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'instagram' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'instagramQr' : ExternalBlob,
  });
  const ProductFilter = IDL.Record({
    'size' : IDL.Opt(ProductSize),
    'isAvailable' : IDL.Opt(IDL.Bool),
    'productType' : IDL.Opt(ProductType),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'searchText' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getFilteredProducts' : IDL.Func(
        [ProductFilter],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getOrderById' : IDL.Func([IDL.Text], [OrderRecord], ['query']),
    'getOrdersByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
    'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([OrderRecord], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminContactInfo' : IDL.Func([ContactInfo], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateProductImages' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };