/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'instagram' : string,
  'email' : string,
  'phone' : string,
  'instagramQr' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface OrderRecord {
  'id' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'products' : Array<Product>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'cashOnDelivery' : null } |
  { 'card' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'productType' : ProductType,
  'sizes' : Array<ProductSize>,
  'stockCount' : bigint,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ProductFilter {
  'size' : [] | [ProductSize],
  'isAvailable' : [] | [boolean],
  'productType' : [] | [ProductType],
  'maxPrice' : [] | [bigint],
  'searchText' : [] | [string],
  'minPrice' : [] | [bigint],
}
export type ProductSize = { 'L' : null } |
  { 'M' : null } |
  { 'S' : null } |
  { 'XL' : null } |
  { 'XS' : null } |
  { 'XXL' : null } |
  { 'Custom' : string };
export type ProductType = { 'Shirt' : null } |
  { 'Skirt' : null } |
  { 'Pant' : null } |
  { 'Suit' : null } |
  { 'Shorts' : null } |
  { 'Dress' : null } |
  { 'Sweater' : null } |
  { 'TShirt' : null } |
  { 'Jacket' : null } |
  { 'Other' : string } |
  { 'Blazer' : null } |
  { 'Jeans' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getFilteredProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getOrderById' : ActorMethod<[string], OrderRecord>,
  'getOrdersByUser' : ActorMethod<[Principal], Array<OrderRecord>>,
  'getPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getProductById' : ActorMethod<[string], Product>,
  'getStripeConfiguration' : ActorMethod<[], StripeConfiguration>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[OrderRecord], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateProductImages' : ActorMethod<[string, Array<ExternalBlob>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];