/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductSize = IDL.Variant({
  'L' : IDL.Null,
  'M' : IDL.Null,
  'S' : IDL.Null,
  'XL' : IDL.Null,
  'XS' : IDL.Null,
  'XXL' : IDL.Null,
  'Custom' : IDL.Text,
});
export const ProductType = IDL.Variant({
  'Dresses' : IDL.Null,
  'Leggings' : IDL.Null,
  'Tops' : IDL.Null,
  'Sarees' : IDL.Null,
  'Kurtas' : IDL.Null,
  'Other' : IDL.Text,
  'Jeans' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'imageUrls' : IDL.Vec(ExternalBlob),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(ProductSize),
  'category' : ProductType,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const CartItem = IDL.Record({
  'size' : ProductSize,
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const ShoppingCart = IDL.Record({
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const CustomerProfile = IDL.Record({
  'username' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductFilter = IDL.Record({
  'inStock' : IDL.Opt(IDL.Bool),
  'size' : IDL.Opt(ProductSize),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'searchText' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ProductType),
  'minPrice' : IDL.Opt(IDL.Nat),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'size' : ProductSize,
  'productId' : IDL.Text,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : IDL.Text,
  'createdAt' : IDL.Int,
  'customerAddress' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrUpdateCart' : IDL.Func([IDL.Text, ShoppingCart], [], []),
  'deleteCart' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCartByCustomerId' : IDL.Func([IDL.Text], [ShoppingCart], ['query']),
  'getFilteredProducts' : IDL.Func(
      [ProductFilter],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
  'getOrdersByCustomerId' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
  'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
  'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([Order], [], []),
  'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUpiId' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateProductImages' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductSize = IDL.Variant({
    'L' : IDL.Null,
    'M' : IDL.Null,
    'S' : IDL.Null,
    'XL' : IDL.Null,
    'XS' : IDL.Null,
    'XXL' : IDL.Null,
    'Custom' : IDL.Text,
  });
  const ProductType = IDL.Variant({
    'Dresses' : IDL.Null,
    'Leggings' : IDL.Null,
    'Tops' : IDL.Null,
    'Sarees' : IDL.Null,
    'Kurtas' : IDL.Null,
    'Other' : IDL.Text,
    'Jeans' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'imageUrls' : IDL.Vec(ExternalBlob),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(ProductSize),
    'category' : ProductType,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const CartItem = IDL.Record({
    'size' : ProductSize,
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const ShoppingCart = IDL.Record({
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const CustomerProfile = IDL.Record({
    'username' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductFilter = IDL.Record({
    'inStock' : IDL.Opt(IDL.Bool),
    'size' : IDL.Opt(ProductSize),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'searchText' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ProductType),
    'minPrice' : IDL.Opt(IDL.Nat),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'size' : ProductSize,
    'productId' : IDL.Text,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'customerPhone' : IDL.Text,
    'createdAt' : IDL.Int,
    'customerAddress' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrUpdateCart' : IDL.Func([IDL.Text, ShoppingCart], [], []),
    'deleteCart' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCartByCustomerId' : IDL.Func([IDL.Text], [ShoppingCart], ['query']),
    'getFilteredProducts' : IDL.Func(
        [ProductFilter],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getOrderById' : IDL.Func([IDL.Text], [Order], ['query']),
    'getOrdersByCustomerId' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getPaymentMethods' : IDL.Func([], [IDL.Vec(PaymentMethod)], ['query']),
    'getProductById' : IDL.Func([IDL.Text], [Product], ['query']),
    'getStripeConfiguration' : IDL.Func([], [StripeConfiguration], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([Order], [], []),
    'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUpiId' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateProductImages' : IDL.Func([IDL.Text, IDL.Vec(ExternalBlob)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };