/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'size' : ProductSize,
  'productId' : string,
  'quantity' : bigint,
}
export interface CustomerProfile {
  'username' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'customerPhone' : string,
  'createdAt' : bigint,
  'customerAddress' : string,
  'totalAmount' : bigint,
  'customerId' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'size' : ProductSize,
  'productId' : string,
  'productName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PaymentMethod = { 'upi' : null } |
  { 'cashOnDelivery' : null } |
  { 'card' : null };
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'imageUrls' : Array<ExternalBlob>,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'sizes' : Array<ProductSize>,
  'category' : ProductType,
  'price' : bigint,
}
export interface ProductFilter {
  'inStock' : [] | [boolean],
  'size' : [] | [ProductSize],
  'maxPrice' : [] | [bigint],
  'searchText' : [] | [string],
  'category' : [] | [ProductType],
  'minPrice' : [] | [bigint],
}
export type ProductSize = { 'L' : null } |
  { 'M' : null } |
  { 'S' : null } |
  { 'XL' : null } |
  { 'XS' : null } |
  { 'XXL' : null } |
  { 'Custom' : string };
export type ProductType = { 'Dresses' : null } |
  { 'Leggings' : null } |
  { 'Tops' : null } |
  { 'Sarees' : null } |
  { 'Kurtas' : null } |
  { 'Other' : string } |
  { 'Jeans' : null };
export interface ShoppingCart {
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'customerId' : string,
  'items' : Array<CartItem>,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrUpdateCart' : ActorMethod<[string, ShoppingCart], undefined>,
  'deleteCart' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCartByCustomerId' : ActorMethod<[string], ShoppingCart>,
  'getFilteredProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'getOrderById' : ActorMethod<[string], Order>,
  'getOrdersByCustomerId' : ActorMethod<[string], Array<Order>>,
  'getPaymentMethods' : ActorMethod<[], Array<PaymentMethod>>,
  'getProductById' : ActorMethod<[string], Product>,
  'getStripeConfiguration' : ActorMethod<[], StripeConfiguration>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUpiId' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Order], undefined>,
  'saveCallerUserProfile' : ActorMethod<[CustomerProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUpiId' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateProductImages' : ActorMethod<[string, Array<ExternalBlob>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];