/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShoppingCart {
    createdAt: bigint;
    updatedAt: bigint;
    customerId: string;
    items: Array<CartItem>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type ProductType = {
    __kind__: "Dresses";
    Dresses: null;
} | {
    __kind__: "Leggings";
    Leggings: null;
} | {
    __kind__: "Tops";
    Tops: null;
} | {
    __kind__: "Sarees";
    Sarees: null;
} | {
    __kind__: "Kurtas";
    Kurtas: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Jeans";
    Jeans: null;
};
export interface OrderItem {
    size: ProductSize;
    productId: string;
    productName: string;
    quantity: bigint;
    price: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CustomerProfile {
    username: string;
    createdAt: bigint;
    email: string;
    address: string;
    phone: string;
}
export interface Order {
    id: string;
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: bigint;
    customerAddress: string;
    totalAmount: bigint;
    customerId: string;
    items: Array<OrderItem>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ProductFilter {
    inStock?: boolean;
    size?: ProductSize;
    maxPrice?: bigint;
    searchText?: string;
    category?: ProductType;
    minPrice?: bigint;
}
export type ProductSize = {
    __kind__: "L";
    L: null;
} | {
    __kind__: "M";
    M: null;
} | {
    __kind__: "S";
    S: null;
} | {
    __kind__: "XL";
    XL: null;
} | {
    __kind__: "XS";
    XS: null;
} | {
    __kind__: "XXL";
    XXL: null;
} | {
    __kind__: "Custom";
    Custom: string;
};
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface CartItem {
    size: ProductSize;
    productId: string;
    quantity: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Product {
    id: string;
    stockQuantity: bigint;
    imageUrls: Array<ExternalBlob>;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<ProductSize>;
    category: ProductType;
    price: bigint;
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    upi = "upi",
    cashOnDelivery = "cashOnDelivery",
    card = "card"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addProduct(product: Product): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrUpdateCart(customerId: string, cart: ShoppingCart): Promise<void>;
    deleteCart(customerId: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<CustomerProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCartByCustomerId(customerId: string): Promise<ShoppingCart>;
    getFilteredProducts(filter: ProductFilter): Promise<Array<Product>>;
    getOrderById(id: string): Promise<Order>;
    getOrdersByCustomerId(customerId: string): Promise<Array<Order>>;
    getPaymentMethods(): Promise<Array<PaymentMethod>>;
    getProductById(id: string): Promise<Product>;
    getStripeConfiguration(): Promise<StripeConfiguration>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUpiId(): Promise<string>;
    getUserProfile(user: Principal): Promise<CustomerProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    placeOrder(order: Order): Promise<void>;
    saveCallerUserProfile(profile: CustomerProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    setUpiId(id: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateOrderStatus(id: string, status: OrderStatus): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateProductImages(id: string, images: Array<ExternalBlob>): Promise<void>;
}
import type { CartItem as _CartItem, CustomerProfile as _CustomerProfile, ExternalBlob as _ExternalBlob, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, Product as _Product, ProductFilter as _ProductFilter, ProductSize as _ProductSize, ProductType as _ProductType, ShoppingCart as _ShoppingCart, StripeSessionStatus as _StripeSessionStatus, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrUpdateCart(arg0: string, arg1: ShoppingCart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateCart(arg0, to_candid_ShoppingCart_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateCart(arg0, to_candid_ShoppingCart_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCart(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCart(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCartByCustomerId(arg0: string): Promise<ShoppingCart> {
        if (this.processError) {
            try {
                const result = await this.actor.getCartByCustomerId(arg0);
                return from_candid_ShoppingCart_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCartByCustomerId(arg0);
            return from_candid_ShoppingCart_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredProducts(to_candid_ProductFilter_n42(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredProducts(to_candid_ProductFilter_n42(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: string): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_Order_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_Order_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByCustomerId(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCustomerId(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCustomerId(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentMethods(): Promise<Array<PaymentMethod>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentMethods();
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentMethods();
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: string): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_Product_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_Product_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeConfiguration(): Promise<StripeConfiguration> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeConfiguration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeConfiguration();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpiId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpiId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpiId();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<CustomerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async placeOrder(arg0: Order): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_Order_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_Order_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: CustomerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async setUpiId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUpiId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUpiId(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: string, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n61(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n61(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_Product_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProductImages(arg0: string, arg1: Array<ExternalBlob>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductImages(arg0, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductImages(arg0, await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CartItem_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_OrderItem_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ProductSize_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductSize): ProductSize {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ShoppingCart_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShoppingCart): ShoppingCart {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerProfile]): CustomerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    stockQuantity: bigint;
    imageUrls: Array<_ExternalBlob>;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<_ProductSize>;
    category: _ProductType;
    price: bigint;
}): Promise<{
    id: string;
    stockQuantity: bigint;
    imageUrls: Array<ExternalBlob>;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<ProductSize>;
    category: ProductType;
    price: bigint;
}> {
    return {
        id: value.id,
        stockQuantity: value.stockQuantity,
        imageUrls: await from_candid_vec_n27(_uploadFile, _downloadFile, value.imageUrls),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        sizes: from_candid_vec_n29(_uploadFile, _downloadFile, value.sizes),
        category: from_candid_ProductType_n32(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    updatedAt: bigint;
    customerId: string;
    items: Array<_CartItem>;
}): {
    createdAt: bigint;
    updatedAt: bigint;
    customerId: string;
    items: Array<CartItem>;
} {
    return {
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        customerId: value.customerId,
        items: from_candid_vec_n39(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: _ProductSize;
    productId: string;
    quantity: bigint;
}): {
    size: ProductSize;
    productId: string;
    quantity: bigint;
} {
    return {
        size: from_candid_ProductSize_n30(_uploadFile, _downloadFile, value.size),
        productId: value.productId,
        quantity: value.quantity
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    createdAt: bigint;
    customerAddress: string;
    totalAmount: bigint;
    customerId: string;
    items: Array<_OrderItem>;
}): {
    id: string;
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: bigint;
    customerAddress: string;
    totalAmount: bigint;
    customerId: string;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n46(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n48(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        customerAddress: value.customerAddress,
        totalAmount: value.totalAmount,
        customerId: value.customerId,
        items: from_candid_vec_n50(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: _ProductSize;
    productId: string;
    productName: string;
    quantity: bigint;
    price: bigint;
}): {
    size: ProductSize;
    productId: string;
    productName: string;
    quantity: bigint;
    price: bigint;
} {
    return {
        size: from_candid_ProductSize_n30(_uploadFile, _downloadFile, value.size),
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        price: value.price
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    L: null;
} | {
    M: null;
} | {
    S: null;
} | {
    XL: null;
} | {
    XS: null;
} | {
    XXL: null;
} | {
    Custom: string;
}): {
    __kind__: "L";
    L: null;
} | {
    __kind__: "M";
    M: null;
} | {
    __kind__: "S";
    S: null;
} | {
    __kind__: "XL";
    XL: null;
} | {
    __kind__: "XS";
    XS: null;
} | {
    __kind__: "XXL";
    XXL: null;
} | {
    __kind__: "Custom";
    Custom: string;
} {
    return "L" in value ? {
        __kind__: "L",
        L: value.L
    } : "M" in value ? {
        __kind__: "M",
        M: value.M
    } : "S" in value ? {
        __kind__: "S",
        S: value.S
    } : "XL" in value ? {
        __kind__: "XL",
        XL: value.XL
    } : "XS" in value ? {
        __kind__: "XS",
        XS: value.XS
    } : "XXL" in value ? {
        __kind__: "XXL",
        XXL: value.XXL
    } : "Custom" in value ? {
        __kind__: "Custom",
        Custom: value.Custom
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Dresses: null;
} | {
    Leggings: null;
} | {
    Tops: null;
} | {
    Sarees: null;
} | {
    Kurtas: null;
} | {
    Other: string;
} | {
    Jeans: null;
}): {
    __kind__: "Dresses";
    Dresses: null;
} | {
    __kind__: "Leggings";
    Leggings: null;
} | {
    __kind__: "Tops";
    Tops: null;
} | {
    __kind__: "Sarees";
    Sarees: null;
} | {
    __kind__: "Kurtas";
    Kurtas: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Jeans";
    Jeans: null;
} {
    return "Dresses" in value ? {
        __kind__: "Dresses",
        Dresses: value.Dresses
    } : "Leggings" in value ? {
        __kind__: "Leggings",
        Leggings: value.Leggings
    } : "Tops" in value ? {
        __kind__: "Tops",
        Tops: value.Tops
    } : "Sarees" in value ? {
        __kind__: "Sarees",
        Sarees: value.Sarees
    } : "Kurtas" in value ? {
        __kind__: "Kurtas",
        Kurtas: value.Kurtas
    } : "Other" in value ? {
        __kind__: "Other",
        Other: value.Other
    } : "Jeans" in value ? {
        __kind__: "Jeans",
        Jeans: value.Jeans
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    cashOnDelivery: null;
} | {
    card: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "cashOnDelivery" in value ? PaymentMethod.cashOnDelivery : "card" in value ? PaymentMethod.card : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n57(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductSize>): Array<ProductSize> {
    return value.map((x)=>from_candid_ProductSize_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentMethod>): Array<PaymentMethod> {
    return value.map((x)=>from_candid_PaymentMethod_n48(_uploadFile, _downloadFile, x));
}
function to_candid_CartItem_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_OrderItem_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItem): _OrderItem {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_ProductSize_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductSize): _ProductSize {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ShoppingCart_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShoppingCart): _ShoppingCart {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    updatedAt: bigint;
    customerId: string;
    items: Array<CartItem>;
}): {
    createdAt: bigint;
    updatedAt: bigint;
    customerId: string;
    items: Array<_CartItem>;
} {
    return {
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        customerId: value.customerId,
        items: to_candid_vec_n21(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: ProductSize;
    productId: string;
    quantity: bigint;
}): {
    size: _ProductSize;
    productId: string;
    quantity: bigint;
} {
    return {
        size: to_candid_ProductSize_n13(_uploadFile, _downloadFile, value.size),
        productId: value.productId,
        quantity: value.quantity
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock?: boolean;
    size?: ProductSize;
    maxPrice?: bigint;
    searchText?: string;
    category?: ProductType;
    minPrice?: bigint;
}): {
    inStock: [] | [boolean];
    size: [] | [_ProductSize];
    maxPrice: [] | [bigint];
    searchText: [] | [string];
    category: [] | [_ProductType];
    minPrice: [] | [bigint];
} {
    return {
        inStock: value.inStock ? candid_some(value.inStock) : candid_none(),
        size: value.size ? candid_some(to_candid_ProductSize_n13(_uploadFile, _downloadFile, value.size)) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        searchText: value.searchText ? candid_some(value.searchText) : candid_none(),
        category: value.category ? candid_some(to_candid_ProductType_n15(_uploadFile, _downloadFile, value.category)) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    customerPhone: string;
    createdAt: bigint;
    customerAddress: string;
    totalAmount: bigint;
    customerId: string;
    items: Array<OrderItem>;
}): {
    id: string;
    customerName: string;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    customerPhone: string;
    createdAt: bigint;
    customerAddress: string;
    totalAmount: bigint;
    customerId: string;
    items: Array<_OrderItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_OrderStatus_n61(_uploadFile, _downloadFile, value.status),
        paymentMethod: to_candid_PaymentMethod_n63(_uploadFile, _downloadFile, value.paymentMethod),
        customerPhone: value.customerPhone,
        createdAt: value.createdAt,
        customerAddress: value.customerAddress,
        totalAmount: value.totalAmount,
        customerId: value.customerId,
        items: to_candid_vec_n65(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: ProductSize;
    productId: string;
    productName: string;
    quantity: bigint;
    price: bigint;
}): {
    size: _ProductSize;
    productId: string;
    productName: string;
    quantity: bigint;
    price: bigint;
} {
    return {
        size: to_candid_ProductSize_n13(_uploadFile, _downloadFile, value.size),
        productId: value.productId,
        productName: value.productName,
        quantity: value.quantity,
        price: value.price
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    stockQuantity: bigint;
    imageUrls: Array<ExternalBlob>;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<ProductSize>;
    category: ProductType;
    price: bigint;
}): Promise<{
    id: string;
    stockQuantity: bigint;
    imageUrls: Array<_ExternalBlob>;
    name: string;
    createdAt: bigint;
    description: string;
    sizes: Array<_ProductSize>;
    category: _ProductType;
    price: bigint;
}> {
    return {
        id: value.id,
        stockQuantity: value.stockQuantity,
        imageUrls: await to_candid_vec_n10(_uploadFile, _downloadFile, value.imageUrls),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        sizes: to_candid_vec_n12(_uploadFile, _downloadFile, value.sizes),
        category: to_candid_ProductType_n15(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "L";
    L: null;
} | {
    __kind__: "M";
    M: null;
} | {
    __kind__: "S";
    S: null;
} | {
    __kind__: "XL";
    XL: null;
} | {
    __kind__: "XS";
    XS: null;
} | {
    __kind__: "XXL";
    XXL: null;
} | {
    __kind__: "Custom";
    Custom: string;
}): {
    L: null;
} | {
    M: null;
} | {
    S: null;
} | {
    XL: null;
} | {
    XS: null;
} | {
    XXL: null;
} | {
    Custom: string;
} {
    return value.__kind__ === "L" ? {
        L: value.L
    } : value.__kind__ === "M" ? {
        M: value.M
    } : value.__kind__ === "S" ? {
        S: value.S
    } : value.__kind__ === "XL" ? {
        XL: value.XL
    } : value.__kind__ === "XS" ? {
        XS: value.XS
    } : value.__kind__ === "XXL" ? {
        XXL: value.XXL
    } : value.__kind__ === "Custom" ? {
        Custom: value.Custom
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "Dresses";
    Dresses: null;
} | {
    __kind__: "Leggings";
    Leggings: null;
} | {
    __kind__: "Tops";
    Tops: null;
} | {
    __kind__: "Sarees";
    Sarees: null;
} | {
    __kind__: "Kurtas";
    Kurtas: null;
} | {
    __kind__: "Other";
    Other: string;
} | {
    __kind__: "Jeans";
    Jeans: null;
}): {
    Dresses: null;
} | {
    Leggings: null;
} | {
    Tops: null;
} | {
    Sarees: null;
} | {
    Kurtas: null;
} | {
    Other: string;
} | {
    Jeans: null;
} {
    return value.__kind__ === "Dresses" ? {
        Dresses: value.Dresses
    } : value.__kind__ === "Leggings" ? {
        Leggings: value.Leggings
    } : value.__kind__ === "Tops" ? {
        Tops: value.Tops
    } : value.__kind__ === "Sarees" ? {
        Sarees: value.Sarees
    } : value.__kind__ === "Kurtas" ? {
        Kurtas: value.Kurtas
    } : value.__kind__ === "Other" ? {
        Other: value.Other
    } : value.__kind__ === "Jeans" ? {
        Jeans: value.Jeans
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    cashOnDelivery: null;
} | {
    card: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.cashOnDelivery ? {
        cashOnDelivery: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ProductSize>): Array<_ProductSize> {
    return value.map((x)=>to_candid_ProductSize_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n22(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItem>): Array<_OrderItem> {
    return value.map((x)=>to_candid_OrderItem_n66(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
